In [1]:
import pandas as pd
import numpy as np
import re

In [41]:
tickers = pd.read_csv('../data/tickers.csv')

In [42]:
import yfinance as yf

# Define tickers
tickers = tickers['Symbol'].to_list()

# Download historical data (adjusted close prices)
data = yf.download(tickers, start='2023-01-01', end='2024-01-01')

[*********************100%***********************]  503 of 503 completed

5 Failed downloads:
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2023-01-01 -> 2024-01-01)')
['SW', 'GEV', 'SOLV']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2023-01-01 -> 2024-01-01) (Yahoo error = "Data doesn\'t exist for startDate = 1672549200, endDate = 1704085200")')
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

In [45]:
data_copy = data.copy()
data_copy

Price                       Adj Close                                      \
Ticker                              A        AAPL        ABBV        ABNB
Date
2023-01-03 00:00:00+00:00  148.204651  123.904625  150.570770   84.900002
2023-01-04 00:00:00+00:00  149.814728  125.182617  151.785477   88.720001
2023-01-05 00:00:00+00:00  150.249359  123.855095  151.600021   87.709999
2023-01-06 00:00:00+00:00  145.863678  128.412247  154.437485   88.519997
2023-01-09 00:00:00+00:00  145.666107  128.937286  149.903107   89.239998
...                               ...         ...         ...         ...
2023-12-22 00:00:00+00:00  138.629974  192.868149  149.475891  140.800003
2023-12-26 00:00:00+00:00  138.868332  192.320221  149.167175  138.720001
2023-12-27 00:00:00+00:00  138.878281  192.419830  149.418015  136.550003
2023-12-28 00:00:00+00:00  138.828644  192.848206  149.292603  137.000000
2023-12-29 00:00:00+00:00  138.327164  191.802185  149.504837  136.139999

Price                                                                     \
Ticker                            ABT       ACGL         ACN        ADBE
Date
2023-01-03 00:00:00+00:00  105.328903  62.459999  261.824371  336.920013
2023-01-04 00:00:00+00:00  106.895676  62.770000  260.933105  341.410004
2023-01-05 00:00:00+00:00  106.501572  62.939999  254.771606  328.440002
2023-01-06 00:00:00+00:00  107.972214  63.900002  260.807190  332.750000
2023-01-09 00:00:00+00:00  107.799187  62.669998  265.205444  341.980011
...                               ...        ...         ...         ...
2023-12-22 00:00:00+00:00  106.896759  73.839996  348.842224  598.750000
2023-12-26 00:00:00+00:00  107.092850  73.510002  347.838348  598.260010
2023-12-27 00:00:00+00:00  107.641884  73.540001  348.222168  596.080017
2023-12-28 00:00:00+00:00  108.239944  74.059998  346.027435  595.520020
2023-12-29 00:00:00+00:00  107.916405  74.269997  345.358215  596.599976

Price                                             ...  Volume           \
Ticker                            ADI        ADM  ...     WTW       WY
Date                                              ...
2023-01-03 00:00:00+00:00  157.418777  85.367523  ...  591300  2939100
2023-01-04 00:00:00+00:00  160.771652  82.263252  ...  547200  3287700
2023-01-05 00:00:00+00:00  154.744263  80.206436  ...  328600  2976200
2023-01-06 00:00:00+00:00  160.393723  81.844269  ...  610800  2890600
2023-01-09 00:00:00+00:00  161.924774  81.291977  ...  548300  2511100
...                               ...        ...  ...     ...      ...
2023-12-22 00:00:00+00:00  194.632874  69.621613  ...  328600  2253500
2023-12-26 00:00:00+00:00  196.380707  70.527687  ...  296900  2542300
2023-12-27 00:00:00+00:00  196.854706  70.313354  ...  323300  2109200
2023-12-28 00:00:00+00:00  197.733582  70.410782  ...  265200  2586100
2023-12-29 00:00:00+00:00  196.074585  70.362068  ...  336900  3079100

Price                                                                    \
Ticker                        WYNN      XEL       XOM      XYL      YUM
Date
2023-01-03 00:00:00+00:00  3318600  2684500  15146200   812400  2307100
2023-01-04 00:00:00+00:00  5743600  2265900  18058400   905900  1139400
2023-01-05 00:00:00+00:00  2983000  2104500  15946600  1295700  1078200
2023-01-06 00:00:00+00:00  2901900  2976200  16348100   636200  1559400
2023-01-09 00:00:00+00:00  2751000  2707800  17964600  1224700  1211200
...                            ...      ...       ...      ...      ...
2023-12-22 00:00:00+00:00  1170500  2429300  12921800   829300   991500
2023-12-26 00:00:00+00:00  1150000  2147500  16835100   440300   627500
2023-12-27 00:00:00+00:00  1142200  2865900  14558800  1007700  1050400
2023-12-28 00:00:00+00:00  1233000  2421900  16329300   709100   882500
2023-12-29 00:00:00+00:00  1144800  2813300  17741400   698900  1196800

Price
Ticker                         ZBH    ZBRA      ZTS
Date
2023-01-03 00:00:00+00:00   921100  295400  1840600
2023-01-04 00:00:00+00:00  1389400  311600  1796100
2023-01-05 00:00:00+00:00  2238300  368200  1560900
2023-01-06 00:00:00+00:00  2348900  552700  1761200
2023-01-09 00:00:00+00:00  1423600  535400  1700500
...                            ...     ...      ...
2023-12-22 00:00:00+00:00  1337800  225900  1548400
2023-12-26 00:00:00+00:00  1870700  220000   814600
2023-12-27 00:00:00+00:00  1058600  275700   766400
2023-12-28 00:00:00+00:00   662200  193900   880100
2023-12-29 00:00:00+00:00   849600  251300  1007200

[250 rows x 3018 columns]

In [46]:
data_copy.columns = [' '.join(col).strip() for col in data_copy.columns.values]

In [61]:
data_copy.reset_index(inplace=True)

In [62]:
data_copy

,Date,Adj Close A,Adj Close AAPL,Adj Close ABBV,Adj Close ABNB,Adj Close ABT,Adj Close ACGL,Adj Close ACN,Adj Close ADBE,Adj Close ADI,...,Volume WTW,Volume WY,Volume WYNN,Volume XEL,Volume XOM,Volume XYL,Volume YUM,Volume ZBH,Volume ZBRA,Volume ZTS
0,2023-01-03 00:00:00+00:00,148.204651,123.904625,150.570770,84.900002,105.328903,62.459999,261.824371,336.920013,157.418777,...,591300,2939100,3318600,2684500,15146200,812400,2307100,921100,295400,1840600
1,2023-01-04 00:00:00+00:00,149.814728,125.182617,151.785477,88.720001,106.895676,62.770000,260.933105,341.410004,160.771652,...,547200,3287700,5743600,2265900,18058400,905900,1139400,1389400,311600,1796100
2,2023-01-05 00:00:00+00:00,150.249359,123.855095,151.600021,87.709999,106.501572,62.939999,254.771606,328.440002,154.744263,...,328600,2976200,2983000,2104500,15946600,1295700,1078200,2238300,368200,1560900
3,2023-01-06 00:00:00+00:00,145.863678,128.412247,154.437485,88.519997,107.972214,63.900002,260.807190,332.750000,160.393723,...,610800,2890600,2901900,2976200,16348100,636200,1559400,2348900,552700,1761200
4,2023-01-09 00:00:00+00:00,145.666107,128.937286,149.903107,89.239998,107.799187,62.669998,265.205444,341.980011,161.924774,...,548300,2511100,2751000,2707800,17964600,1224700,1211200,1423600,535400,1700500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2023-12-22 00:00:00+00:00,138.629974,192.868149,149.475891,140.800003,106.896759,73.839996,348.842224,598.750000,194.632874,...,328600,2253500,1170500,2429300,12921800,829300,991500,1337800,225900,1548400
246,2023-12-26 00:00:00+00:00,138.868332,192.320221,149.167175,138.720001,107.092850,73.510002,347.838348,598.260010,196.380707,...,296900,2542300,1150000,2147500,16835100,440300,627500,1870700,220000,814600
247,2023-12-27 00:00:00+00:00,138.878281,192.419830,149.418015,136.550003,107.641884,73.540001,348.222168,596.080017,196.854706,...,323300,2109200,1142200,2865900,14558800,1007700,1050400,1058600,275700,766400
248,2023-12-28 00:00:00+00:00,138.828644,192.848206,149.292603,137.000000,108.239944,74.059998,346.027435,595.520020,197.733582,...,265200,2586100,1233000,2421900,16329300,709100,882500,662200,193900,880100
249,2023-12-29 00:00:00+00:00,138.327164,191.802185,149.504837,136.139999,107.916405,74.269997,345.358215,596.599976,196.074585,...,336900,3079100,1144800,2813300,17741400,698900,1196800,849600,251300,1007200

# Feature Engineering for validation data

In [63]:
adj_close = data_copy.filter(like='Adj Close')

# Calculate exponential moving average for each column

ema = adj_close.ewm(span=20).mean()

# Rename columns

ema.columns = [f'{col} EMA' for col in ema.columns]

# Remove Adj Close from the column names
ema.columns = [col.replace('Adj Close', '') for col in ema.columns]

ema

,A EMA,AAPL EMA,ABBV EMA,ABNB EMA,ABT EMA,ACGL EMA,ACN EMA,ADBE EMA,ADI EMA,ADM EMA,...,WTW EMA,WY EMA,WYNN EMA,XEL EMA,XOM EMA,XYL EMA,YUM EMA,ZBH EMA,ZBRA EMA,ZTS EMA
0,148.204651,123.904625,150.570770,84.900002,105.328903,62.459999,261.824371,336.920013,157.418777,85.367523,...,239.288162,28.644812,84.247192,65.785957,100.414612,108.447273,122.775803,125.504356,260.200012,144.095444
1,149.049941,124.575571,151.208491,86.905501,106.151459,62.622750,261.356457,339.277258,159.179037,83.737781,...,239.959385,28.825118,86.980231,66.081702,100.568048,108.359887,123.649039,126.115217,261.664751,145.182406
2,149.490360,124.311016,151.352259,87.200908,106.280018,62.739242,258.938539,335.297883,157.550614,82.441092,...,240.164468,28.568042,88.047204,65.686967,101.446392,107.201947,123.591161,125.456424,261.075495,144.278842
3,148.443393,125.494978,152.242916,87.581709,106.768529,63.074335,259.477990,334.562349,158.371376,82.268799,...,242.235910,28.791176,89.211545,66.046208,102.242628,107.705609,124.285415,125.020503,264.639167,144.449671
4,147.771591,126.327643,151.676936,87.982835,107.017836,62.976529,260.863412,336.356618,159.230913,82.032514,...,243.855336,28.881508,90.086426,66.417022,102.247421,108.128960,124.575223,124.844170,268.183081,144.413825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,130.794615,192.588037,144.279790,138.928638,103.678460,77.977918,333.952790,602.111536,187.522755,71.455369,...,237.035582,31.842555,87.168027,59.182606,99.098932,106.862788,126.173516,116.237001,249.781333,187.044891
246,131.563540,192.562531,144.745255,138.908768,104.003640,77.552402,335.275224,601.744724,188.366370,71.367019,...,236.935388,32.031796,87.461966,59.254614,99.144977,107.418182,126.379580,116.657779,252.230730,187.667543
247,132.260182,192.548940,145.190280,138.684124,104.350139,77.170269,336.508266,601.205228,189.174783,71.266670,...,236.864479,32.215108,87.692961,59.302194,99.142067,107.992473,126.620442,117.011037,254.474471,188.362919
248,132.885750,192.577442,145.580977,138.523731,104.720597,76.874053,337.414854,600.663780,189.989906,71.185156,...,236.881449,32.412594,88.008695,59.377608,99.002940,108.506402,126.808338,117.377971,256.462617,189.016589
249,133.403980,192.503608,145.954678,138.296709,105.024960,76.626047,338.171364,600.276751,190.569400,71.106767,...,237.074146,32.560570,88.232960,59.447690,98.857564,108.975164,126.991477,117.716583,258.069033,189.627808

In [65]:
# Calculate daily returns for each column
daily_returns = adj_close.pct_change()

# Rename columns to indicate daily returns
daily_returns.columns = [f'{col} Daily Return' for col in daily_returns.columns]

# Remove the Adj Close from the column names
daily_returns.columns = [col.replace('Adj Close', '') for col in daily_returns.columns]

# Make an index column 
daily_returns['Date'] = data_copy['Date']

# Convert date column to python datetime
daily_returns['Date'] = pd.to_datetime(daily_returns['Date'])

# Set all columns except date to numeric
daily_returns = daily_returns.apply(pd.to_numeric, errors='ignore')

# Fill NaN with average of the column
daily_returns = daily_returns.fillna(daily_returns.mean())

daily_returns

/var/folders/yd/y2xd1nbj51gg19hxs58kt7yh0000gn/T/ipykernel_67867/992555061.py:2: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  daily_returns = adj_close.pct_change()
/var/folders/yd/y2xd1nbj51gg19hxs58kt7yh0000gn/T/ipykernel_67867/992555061.py:17: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  daily_returns = daily_returns.apply(pd.to_numeric, errors='ignore')

,A Daily Return,AAPL Daily Return,ABBV Daily Return,ABNB Daily Return,ABT Daily Return,ACGL Daily Return,ACN Daily Return,ADBE Daily Return,ADI Daily Return,ADM Daily Return,...,WY Daily Return,WYNN Daily Return,XEL Daily Return,XOM Daily Return,XYL Daily Return,YUM Daily Return,ZBH Daily Return,ZBRA Daily Return,ZTS Daily Return,Date
0,-0.000135,0.001835,0.000048,0.002252,0.000175,0.000826,0.001207,0.002498,0.001018,-0.000679,...,0.000797,0.000465,-0.000285,0.000003,0.000289,0.000242,-0.000065,0.000541,0.001347,1672704000000000000
1,0.010864,0.010314,0.008067,0.044994,0.014875,0.004963,-0.003404,0.013327,0.021299,-0.036364,...,0.011990,0.061792,0.008563,0.002911,-0.001535,0.013548,0.009271,0.010722,0.014368,1672790400000000000
2,0.002901,-0.010605,-0.001222,-0.011384,-0.003687,0.002708,-0.023613,-0.037990,-0.037490,-0.025003,...,-0.029779,0.004841,-0.020235,0.022374,-0.028393,-0.007616,-0.018527,-0.011141,-0.023563,1672876800000000000
3,-0.029189,0.036794,0.018717,0.009235,0.013809,0.015253,0.023690,0.013123,0.036508,0.020420,...,0.043234,0.024414,0.029607,0.012087,0.035551,0.020282,-0.003014,0.051373,0.015057,1672963200000000000
4,-0.001354,0.004089,-0.029361,0.008134,-0.001603,-0.019249,0.016864,0.027739,0.009546,-0.006748,...,-0.006011,0.008122,0.009679,-0.018637,0.004673,-0.004068,0.002785,0.021469,-0.003928,1673222400000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,0.004534,-0.005547,0.015401,-0.009079,0.005070,-0.004315,0.016344,-0.002316,0.004178,0.007472,...,0.007329,-0.003307,0.008614,0.001769,0.008506,0.000154,0.007605,0.015454,0.001644,1703203200000000000
246,0.001719,-0.002841,-0.002065,-0.014773,0.001834,-0.004469,-0.002878,-0.000818,0.008980,0.013014,...,0.007858,0.006415,0.003062,0.002257,0.008700,0.002000,0.009142,0.022605,0.002667,1703548800000000000
247,0.000072,0.000518,0.001682,-0.015643,0.005127,0.000408,0.001103,-0.003644,0.002414,-0.003039,...,0.003754,-0.004066,-0.003078,-0.004699,0.006689,0.004453,-0.002388,0.001053,0.007161,1703635200000000000
248,-0.000357,0.002226,-0.000839,0.003295,0.005556,0.007071,-0.006303,-0.000939,0.004465,0.001386,...,0.009781,0.012468,0.005687,-0.014460,-0.000525,-0.002446,0.004128,-0.001595,0.001321,1703721600000000000
249,-0.003612,-0.005424,0.001422,-0.006277,-0.002989,0.002836,-0.001934,0.001813,-0.008390,-0.000692,...,-0.009402,-0.007084,0.000323,-0.002096,0.000350,0.001073,0.000576,-0.007336,0.001065,1703808000000000000

In [67]:
# Concatenate the original data with the calculated EMA and daily returns

result = pd.concat([data_copy, ema, daily_returns], axis=1)

# Remove the second date column
result = result.loc[:,~result.columns.duplicated()]
result

,Date,Adj Close A,Adj Close AAPL,Adj Close ABBV,Adj Close ABNB,Adj Close ABT,Adj Close ACGL,Adj Close ACN,Adj Close ADBE,Adj Close ADI,...,WTW Daily Return,WY Daily Return,WYNN Daily Return,XEL Daily Return,XOM Daily Return,XYL Daily Return,YUM Daily Return,ZBH Daily Return,ZBRA Daily Return,ZTS Daily Return
0,2023-01-03 00:00:00+00:00,148.204651,123.904625,150.570770,84.900002,105.328903,62.459999,261.824371,336.920013,157.418777,...,0.000104,0.000797,0.000465,-0.000285,0.000003,0.000289,0.000242,-0.000065,0.000541,0.001347
1,2023-01-04 00:00:00+00:00,149.814728,125.182617,151.785477,88.720001,106.895676,62.770000,260.933105,341.410004,160.771652,...,0.005343,0.011990,0.061792,0.008563,0.002911,-0.001535,0.013548,0.009271,0.010722,0.014368
2,2023-01-05 00:00:00+00:00,150.249359,123.855095,151.600021,87.709999,106.501572,62.939999,254.771606,328.440002,154.744263,...,-0.000203,-0.029779,0.004841,-0.020235,0.022374,-0.028393,-0.007616,-0.018527,-0.011141,-0.023563
3,2023-01-06 00:00:00+00:00,145.863678,128.412247,154.437485,88.519997,107.972214,63.900002,260.807190,332.750000,160.393723,...,0.028364,0.043234,0.024414,0.029607,0.012087,0.035551,0.020282,-0.003014,0.051373,0.015057
4,2023-01-09 00:00:00+00:00,145.666107,128.937286,149.903107,89.239998,107.799187,62.669998,265.205444,341.980011,161.924774,...,0.006432,-0.006011,0.008122,0.009679,-0.018637,0.004673,-0.004068,0.002785,0.021469,-0.003928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2023-12-22 00:00:00+00:00,138.629974,192.868149,149.475891,140.800003,106.896759,73.839996,348.842224,598.750000,194.632874,...,0.007300,0.007329,-0.003307,0.008614,0.001769,0.008506,0.000154,0.007605,0.015454,0.001644
246,2023-12-26 00:00:00+00:00,138.868332,192.320221,149.167175,138.720001,107.092850,73.510002,347.838348,598.260010,196.380707,...,-0.004165,0.007858,0.006415,0.003062,0.002257,0.008700,0.002000,0.009142,0.022605,0.002667
247,2023-12-27 00:00:00+00:00,138.878281,192.419830,149.418015,136.550003,107.641884,73.540001,348.222168,596.080017,196.854706,...,0.000878,0.003754,-0.004066,-0.003078,-0.004699,0.006689,0.004453,-0.002388,0.001053,0.007161
248,2023-12-28 00:00:00+00:00,138.828644,192.848206,149.292603,137.000000,108.239944,74.059998,346.027435,595.520020,197.733582,...,0.003606,0.009781,0.012468,0.005687,-0.014460,-0.000525,-0.002446,0.004128,-0.001595,0.001321
249,2023-12-29 00:00:00+00:00,138.327164,191.802185,149.504837,136.139999,107.916405,74.269997,345.358215,596.599976,196.074585,...,0.007856,-0.009402,-0.007084,0.000323,-0.002096,0.000350,0.001073,0.000576,-0.007336,0.001065

In [68]:
portfolio_daily_return = adj_close.sum(axis=1).pct_change()

# Linearly interpolate first row
portfolio_daily_return.iloc[0] = portfolio_daily_return.iloc[1]

# Rename the column
portfolio_daily_return.name = 'Portfolio Daily Return'

portfolio_daily_return

0      0.012215
1      0.012215
2     -0.011844
3      0.022145
4     -0.001074
         ...
245    0.003292
246    0.004680
247    0.001898
248    0.000589
249   -0.001724
Name: Portfolio Daily Return, Length: 250, dtype: float64

In [69]:
result = pd.concat([result, portfolio_daily_return], axis=1)
result

,Date,Adj Close A,Adj Close AAPL,Adj Close ABBV,Adj Close ABNB,Adj Close ABT,Adj Close ACGL,Adj Close ACN,Adj Close ADBE,Adj Close ADI,...,WY Daily Return,WYNN Daily Return,XEL Daily Return,XOM Daily Return,XYL Daily Return,YUM Daily Return,ZBH Daily Return,ZBRA Daily Return,ZTS Daily Return,Portfolio Daily Return
0,2023-01-03 00:00:00+00:00,148.204651,123.904625,150.570770,84.900002,105.328903,62.459999,261.824371,336.920013,157.418777,...,0.000797,0.000465,-0.000285,0.000003,0.000289,0.000242,-0.000065,0.000541,0.001347,0.012215
1,2023-01-04 00:00:00+00:00,149.814728,125.182617,151.785477,88.720001,106.895676,62.770000,260.933105,341.410004,160.771652,...,0.011990,0.061792,0.008563,0.002911,-0.001535,0.013548,0.009271,0.010722,0.014368,0.012215
2,2023-01-05 00:00:00+00:00,150.249359,123.855095,151.600021,87.709999,106.501572,62.939999,254.771606,328.440002,154.744263,...,-0.029779,0.004841,-0.020235,0.022374,-0.028393,-0.007616,-0.018527,-0.011141,-0.023563,-0.011844
3,2023-01-06 00:00:00+00:00,145.863678,128.412247,154.437485,88.519997,107.972214,63.900002,260.807190,332.750000,160.393723,...,0.043234,0.024414,0.029607,0.012087,0.035551,0.020282,-0.003014,0.051373,0.015057,0.022145
4,2023-01-09 00:00:00+00:00,145.666107,128.937286,149.903107,89.239998,107.799187,62.669998,265.205444,341.980011,161.924774,...,-0.006011,0.008122,0.009679,-0.018637,0.004673,-0.004068,0.002785,0.021469,-0.003928,-0.001074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2023-12-22 00:00:00+00:00,138.629974,192.868149,149.475891,140.800003,106.896759,73.839996,348.842224,598.750000,194.632874,...,0.007329,-0.003307,0.008614,0.001769,0.008506,0.000154,0.007605,0.015454,0.001644,0.003292
246,2023-12-26 00:00:00+00:00,138.868332,192.320221,149.167175,138.720001,107.092850,73.510002,347.838348,598.260010,196.380707,...,0.007858,0.006415,0.003062,0.002257,0.008700,0.002000,0.009142,0.022605,0.002667,0.004680
247,2023-12-27 00:00:00+00:00,138.878281,192.419830,149.418015,136.550003,107.641884,73.540001,348.222168,596.080017,196.854706,...,0.003754,-0.004066,-0.003078,-0.004699,0.006689,0.004453,-0.002388,0.001053,0.007161,0.001898
248,2023-12-28 00:00:00+00:00,138.828644,192.848206,149.292603,137.000000,108.239944,74.059998,346.027435,595.520020,197.733582,...,0.009781,0.012468,0.005687,-0.014460,-0.000525,-0.002446,0.004128,-0.001595,0.001321,0.000589
249,2023-12-29 00:00:00+00:00,138.327164,191.802185,149.504837,136.139999,107.916405,74.269997,345.358215,596.599976,196.074585,...,-0.009402,-0.007084,0.000323,-0.002096,0.000350,0.001073,0.000576,-0.007336,0.001065,-0.001724

In [70]:
# Select all columns except the date and the response variable
columns_to_normalize = result.columns[1:-1]

# Normalize the columns
result[columns_to_normalize] = (result[columns_to_normalize] - result[columns_to_normalize].mean()) / result[columns_to_normalize].std()


result

,Date,Adj Close A,Adj Close AAPL,Adj Close ABBV,Adj Close ABNB,Adj Close ABT,Adj Close ACGL,Adj Close ACN,Adj Close ADBE,Adj Close ADI,...,WY Daily Return,WYNN Daily Return,XEL Daily Return,XOM Daily Return,XYL Daily Return,YUM Daily Return,ZBH Daily Return,ZBRA Daily Return,ZTS Daily Return,Portfolio Daily Return
0,2023-01-03 00:00:00+00:00,1.539457,-2.727718,1.461301,-2.959398,0.737189,-1.771679,-1.294520,-1.343630,-2.150772,...,0.000000,2.827046e-18,0.000000,2.571616e-18,0.000000,-2.669680e-18,2.097431e-18,4.186754e-18,1.378145e-17,0.012215
1,2023-01-04 00:00:00+00:00,1.655186,-2.654430,1.636923,-2.674714,1.028925,-1.725814,-1.330595,-1.296746,-1.796524,...,0.744910,3.198160e+00,0.713405,1.858418e-01,-0.124370,1.310524e+00,7.224434e-01,3.931738e-01,8.275507e-01,0.012215
2,2023-01-05 00:00:00+00:00,1.686426,-2.730558,1.610110,-2.749984,0.955542,-1.700662,-1.579993,-1.432177,-2.433348,...,-2.034846,2.281614e-01,-1.608498,1.429879e+00,-1.956126,-7.739229e-01,-1.428624e+00,-4.511076e-01,-1.583227e+00,-0.011844
3,2023-01-06 00:00:00+00:00,1.371194,-2.469223,2.020351,-2.689619,1.229379,-1.558629,-1.335692,-1.387173,-1.836454,...,2.824279,1.248922e+00,2.410149,7.723533e-01,2.404944,1.973812e+00,-2.281788e-01,1.962929e+00,8.713005e-01,0.022145
4,2023-01-09 00:00:00+00:00,1.356993,-2.439114,1.364770,-2.635961,1.197161,-1.740609,-1.157665,-1.290794,-1.674691,...,-0.453032,3.993082e-01,0.803366,-1.191423e+00,0.299042,-4.244877e-01,2.205139e-01,8.081546e-01,-3.353074e-01,-0.001074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,2023-12-22 00:00:00+00:00,0.851252,1.227077,1.303003,1.206533,1.029127,-0.087996,2.227685,1.390373,1.781082,...,0.434760,-1.967261e-01,0.717494,1.129037e-01,0.560406,-8.647811e-03,5.935640e-01,5.758740e-01,1.884339e-02,0.003292
246,2023-12-26 00:00:00+00:00,0.868384,1.195655,1.258369,1.051521,1.065640,-0.136819,2.187051,1.385256,1.965750,...,0.469943,3.102454e-01,0.269840,1.440656e-01,0.573677,1.731556e-01,7.124978e-01,8.520283e-01,8.386570e-02,0.004680
247,2023-12-27 00:00:00+00:00,0.869099,1.201368,1.294635,0.889803,1.167871,-0.132381,2.202587,1.362493,2.015830,...,0.196809,-2.363113e-01,-0.225172,-3.005582e-01,0.436502,4.147371e-01,-1.797775e-01,1.976590e-02,3.694915e-01,0.001898
248,2023-12-28 00:00:00+00:00,0.865532,1.225933,1.276503,0.923339,1.279231,-0.055446,2.113751,1.356646,2.108688,...,0.597939,6.259529e-01,0.481552,-9.244159e-01,-0.055466,-2.647124e-01,3.244580e-01,-8.249265e-02,-1.709141e-03,0.000589
249,2023-12-29 00:00:00+00:00,0.829486,1.165948,1.307188,0.859247,1.218987,-0.024377,2.086663,1.367922,1.933406,...,-0.678702,-3.936894e-01,0.049053,-1.341588e-01,0.004176,8.183013e-02,4.958159e-02,-3.041779e-01,-1.794426e-02,-0.001724

In [71]:
result.to_csv('../data/validation.csv', index=False)

In [14]:
# Read validation data

data = pd.read_csv('../data/validation.csv')

In [15]:
na_cols = []
for col in data.columns:
    if data[col].isna().any():
        na_cols.append(col)

na_cols

['Adj Close BF.B',
 'Adj Close BRK.B',
 'Adj Close GEV',
 'Adj Close KVUE',
 'Adj Close SOLV',
 'Adj Close SW',
 'Adj Close VLTO',
 'Close BF.B',
 'Close BRK.B',
 'Close GEV',
 'Close KVUE',
 'Close SOLV',
 'Close SW',
 'Close VLTO',
 'High BF.B',
 'High BRK.B',
 'High GEV',
 'High KVUE',
 'High SOLV',
 'High SW',
 'High VLTO',
 'Low BF.B',
 'Low BRK.B',
 'Low GEV',
 'Low KVUE',
 'Low SOLV',
 'Low SW',
 'Low VLTO',
 'Open BF.B',
 'Open BRK.B',
 'Open GEV',
 'Open KVUE',
 'Open SOLV',
 'Open SW',
 'Open VLTO',
 'Volume BF.B',
 'Volume BRK.B',
 'Volume GEV',
 'Volume KVUE',
 'Volume SOLV',
 'Volume SW',
 'Volume VLTO',
 ' BF.B EMA',
 ' BRK.B EMA',
 ' GEV EMA',
 ' KVUE EMA',
 ' SOLV EMA',
 ' SW EMA',
 ' VLTO EMA',
 ' BF.B Daily Return',
 ' BRK.B Daily Return',
 ' GEV Daily Return',
 ' SOLV Daily Return',
 ' SW Daily Return']

In [11]:
# Check if there are NA values in any column

data[data.isna().any(axis=1)]


# Linearly interpolate the NA values
data = data.interpolate()

# Get how many columns have NA values
na_cols = []
for col in data.columns:
    if data[col].isna().any():
        na_cols.append(col)
na_cols

/var/folders/yd/y2xd1nbj51gg19hxs58kt7yh0000gn/T/ipykernel_12640/4143770700.py:7: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data = data.interpolate()

['Adj Close BF.B',
 'Adj Close BRK.B',
 'Adj Close GEV',
 'Adj Close KVUE',
 'Adj Close SOLV',
 'Adj Close SW',
 'Adj Close VLTO',
 'Close BF.B',
 'Close BRK.B',
 'Close GEV',
 'Close KVUE',
 'Close SOLV',
 'Close SW',
 'Close VLTO',
 'High BF.B',
 'High BRK.B',
 'High GEV',
 'High KVUE',
 'High SOLV',
 'High SW',
 'High VLTO',
 'Low BF.B',
 'Low BRK.B',
 'Low GEV',
 'Low KVUE',
 'Low SOLV',
 'Low SW',
 'Low VLTO',
 'Open BF.B',
 'Open BRK.B',
 'Open GEV',
 'Open KVUE',
 'Open SOLV',
 'Open SW',
 'Open VLTO',
 'Volume BF.B',
 'Volume BRK.B',
 'Volume GEV',
 'Volume KVUE',
 'Volume SOLV',
 'Volume SW',
 'Volume VLTO',
 ' BF.B EMA',
 ' BRK.B EMA',
 ' GEV EMA',
 ' KVUE EMA',
 ' SOLV EMA',
 ' SW EMA',
 ' VLTO EMA',
 ' BF.B Daily Return',
 ' BRK.B Daily Return',
 ' GEV Daily Return',
 ' SOLV Daily Return',
 ' SW Daily Return']

In [13]:
data[' SOLV EMA']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
245   NaN
246   NaN
247   NaN
248   NaN
249   NaN
Name:  SOLV EMA, Length: 250, dtype: float64

In [17]:
# Fill NaN values with the average of the column except Date and Portfolio Daily Return

for col in data.columns:
    if col not in ['Date', 'Portfolio Daily Return']:
        data[col] = data[col].fillna(data[col].mean())



na_cols = []
for col in data.columns:
    if data[col].isna().any():
        na_cols.append(col)
na_cols

['Adj Close BF.B',
 'Adj Close BRK.B',
 'Adj Close GEV',
 'Adj Close SOLV',
 'Adj Close SW',
 'Close BF.B',
 'Close BRK.B',
 'Close GEV',
 'Close SOLV',
 'Close SW',
 'High BF.B',
 'High BRK.B',
 'High GEV',
 'High SOLV',
 'High SW',
 'Low BF.B',
 'Low BRK.B',
 'Low GEV',
 'Low SOLV',
 'Low SW',
 'Open BF.B',
 'Open BRK.B',
 'Open GEV',
 'Open SOLV',
 'Open SW',
 'Volume BF.B',
 'Volume BRK.B',
 'Volume GEV',
 'Volume SOLV',
 'Volume SW',
 ' BF.B EMA',
 ' BRK.B EMA',
 ' GEV EMA',
 ' SOLV EMA',
 ' SW EMA',
 ' BF.B Daily Return',
 ' BRK.B Daily Return',
 ' GEV Daily Return',
 ' SOLV Daily Return',
 ' SW Daily Return']

In [18]:
# Fill NaN values with 0 

data = data.fillna(0)



na_cols = []
for col in data.columns:
    if data[col].isna().any():
        na_cols.append(col)
na_cols

[]

In [19]:
data.to_csv('../data/validation.csv', index=False)